// src/components/SliderSlide.tsx
import type { CSSProperties, HTMLAttributes, ReactNode } from 'react';
import { slideWidthExpr, toCssUnit } from '../core';
import type { SliderInjectedOptions } from '../types';

type SliderSlideProps = HTMLAttributes<HTMLDivElement> &
  SliderInjectedOptions & { children?: ReactNode };

export function SliderSlide({
  className,
  style,
  children,
  __sliderOptions,
  __cssId,
  ...rest
}: SliderSlideProps) {
  if (!__sliderOptions) {
    return (
      <div className={className} style={style} {...rest}>
        {children}
      </div>
    );
  }

  // When __cssId is set, a <style> tag generated by <Slider> provides the responsive
  // width via CSS media queries. Setting width inline would override those rules.
  if (__cssId !== undefined) {
    const slideStyle: CSSProperties = {
      minWidth: 0,
      flexShrink: 0,
      scrollSnapAlign: 'start',
      ...style,
    };
    return (
      <div className={className} style={slideStyle} {...rest}>
        {children}
      </div>
    );
  }

  const fixedWidth = toCssUnit(__sliderOptions.fixedWidth);
  const gap = toCssUnit(__sliderOptions.gap) ?? '0px';
  // v8 ignore next -- perPage is always set by resolveOptions defaults; `?? 1` is unreachable
  const perPage = __sliderOptions.perPage ?? 1;
  const width = fixedWidth ? fixedWidth : slideWidthExpr(perPage, gap);
  const slideStyle: CSSProperties = {
    minWidth: 0,
    flexShrink: 0,
    scrollSnapAlign: 'start',
    width,
    ...style,
  };
  return (
    <div className={className} style={slideStyle} {...rest}>
      {children}
    </div>
  );
}

export default SliderSlide;
